## Analysis

As noted above, we used several regression methods on the dataset Credit.

#### OLS

```{r results= 'asis', echo =FALSE}
tb_OLS <- xtable(OLS_reg, caption = 'Multiple Ordinary Linear Regression (OLS)')
print(tb_OLS, comment= FALSE)
```

```{r echo = FALSE, results = 'hide', message= FALSE}
#This chunck is here so the later code chuncks work
ridge_final 
```

```{r results= 'asis', echo =FALSE}
tb_ridge <- xtable(as.matrix(ridge_final), caption = 'Final Coefficents for Ridge Regression')
print(tb_ridge, comment= FALSE)
```

```{r results= 'asis', echo =FALSE}
tb_lasso <- xtable(as.matrix(lasso_final), caption = 'Final Coefficents for Lasso Regression')
print(tb_lasso, comment= FALSE)
```



```{r results= 'asis', echo =FALSE}
pcr_indice = ((pcr_best-1)*11 +1):(pcr_best*11)
pls_indice = ((pls_best-1)*11 +1):(pls_best*11)
coef_table <- data.frame(coef(OLS_reg), sapply(c(ridge_final, lasso_final),as.matrix),
	c(NA, coef(pcr_final)[pcr_indice]),
	c(NA, coef(pls_final)[pls_indice]))

rownames(coef_table) =  names(coef(OLS_reg))
colnames(coef_table) = c("OLS", "Ridge", "Lasso", "PCR", "PLS")

tb_all <- xtable(coef_table)
print(tb_all, comment = FALSE)
```


```{r results= 'asis', echo =FALSE}
MSE <- c(OLS_tMSE, ridge_tMSE, lasso_tMSE, pcr_tMSE, pls_tMSE)
names(MSE) = c("OLS", "Ridge", "Lasso", "PCR", "PLS")

tb_mse <- xtable(t(data.frame(MSE)),digits = 9)
print(tb_mse, comment = FALSE)
```




